title: Sammi Opalewski 
logo: "/images/IMG_0565.JPEG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Edit these links below   
  <br>
  in _config.yml 
  <br><br>
  <a href="https://www.linkedin.com/in/samanthaopalewski/">LinkedIn</a> 
  <br>
  <a href="https://www.GitHub.com/sammiopalewski/">GitHub</a>  
  <br>

  
theme: jekyll-theme-minimal
